bbc/peaks.js

README.md, package.json, src/main.js, src/main/waveform/waveform.axis.js
This also fixes a regression from the KineticJS upgrade, which broke painting the axis in anything other than black. Using `setAttr` on the context makes it work as expected and now the axis is painted in the correct color.
=> Make the axis label and gridline colors configurable

src/main/views/waveform.overview.js
You have a typo in waveform.overview.js, this fixes it :)
=> Fix typo, seeking instead of seaking

README.md, package.json, src/main.js, src/main/views/waveform.overview.js, src/main/views/waveform.zoomview.js, src/main/views/zooms/static.js
We have some really large (3+ hours at 256 samples/pixel!) audio files where zoom is never really going to be performant, so we wanted to be able to turn zoom off.
This PR also adds safety checks (some of which are already in #118, see commit 1395290) to prevent doing things which are incorrect.
=> Allow alternate zoom adapters, add a static (non-animated) zoom adapter, add more safety checks

README.md, src/main.js, src/main/views/waveform.overview.js, src/main/views/waveform.zoomview.js
This PR adds more configuration options for setting colors. Specifically:
* The overview highlight rectangle (if you have a better name, let me know). The grey blob in the overview.
* The text color of the playhead.
=> Make more colors configurable

.travis.yml, package.json, src/main/markers/waveform.segments.js
Drawing within `updateSegmentWaveform` performs too many renders.
fix #119
=> Explicit segment draw on drag resize

src/main/views/waveform.overview.js
`createWaveform` adds the waveform layer to the stage already, but then we re-add it to the stage. I'm unsure exactly what effect this has (@johvet probably does), but it definitely seems incorrect. The UI layer also needed to be moved on top of the other layers, because the waveform was covering up the playhead and other important bits.
=> Bugfix: Don't add waveform layer to the overview stage twice and ensure the UI layer is on top

src/main/markers/waveform.segments.js
I would find it useful for there to be an event that's fired when a segment handle is dragged. I couldn't see events being tested anywhere, so i haven't added a test. I hope I'm contributing this in a sensible way, and in the correct place! Let me know if not.
=> Add event for handle being dragged

.travis.yml, test/audioElement.html
I think the second server is responsible for random test failures on Travis, we can probably make it more reliable just by serving everything through Karma.
(Unless the separate server was intentional, as an integration test for CORS..?)
=> Serve media from Karma during tests

README.md, src/main.js, src/main/markers/waveform.points.js, src/main/markers/waveform.segments.js, test/unit/api-points-spec.js, test/unit/api-segments-spec.js, test/unit/waveform-segments-spec.js
It now warns on `addSegment(0, 10, …)` - a segment object should be passed instead.
eg - 
```js
addSegment({startTime: 0, endTime: 10, …})
addSegment([{startTime: 0, endTime: 10, …}, {startTime: 10, endTime: 20, …}])
```
---
This is something of a work in progress - I want to change `points.add` to follow the same signature, but thought I should get feedback on whether this is going in the right direction first.   In particular, I think it's a little weird that `segments.addSegment` now takes a segment-object, but then breaks it back out to spread-arguments for `waveform.segments.createSegment`.   WDYT to just passing the segment-object directly to createSegment ?
(Previously: #141 & #6)
=> Improve `addSegment` signature

src/main/views/waveform.overview.js, src/main/views/waveform.zoomview.js
FastLayer doesn’t support, eg, hit-testing, which makes it way faster when rendering large waveforms.
=> Use Konva.FastLayer for drawing waveforms

src/main/waveform/waveform.core.js
If the XHR fails for some reason (perhaps because of [annoying cross-origin-redirect bugs](https://bugs.webkit.org/show_bug.cgi?id=57600)), the error is quietly swallowed.   How about reporting it via `peaks.emit('error')` ?
=> Report XHR errors

README.md, package.json, src/main.js, src/main/markers/waveform.points.js, src/main/markers/waveform.segments.js, src/main/player/player.js, src/main/views/helpers/mousedraghandler.js, src/main/views/waveform.overview.js, src/main/views/waveform.zoomview.js, src/main/waveform/waveform.core.js, src/main/waveform/waveform.utils.js
This pull request fixes a number of problems with mouse dragging behaviour in the waveform views:
- Dragging to scroll the zoom view causes a jump in position when the mouse pointer moves outside the waveform view (to the left or right)
- Clicking in the overview updates the audio playhead position, but the playhead marker does not move
- Dragging in the overview moves the playhead marker in the zoomview, but does not change the actual audio playhead position, so the two views get out of sync with each other
- Point markers can be dragged beyond the right-hand edge of the waveform view (but not the left-hand edge)
=> Fix mouse dragging behaviour

README.md, package.json
The build process for _peaks.js_ currently outputs:
- `peaks.js` - A UMD-compliant bundle.
- `index.js` - A CommonJS-compliant bundle.
As described in issue #174, using ES2015-compliant import statements (like those presented in the README.md) will fail as the `package.json` file points to a CommonJS-only bundle.
The CommonJS-compliant bundle is not needed as the [UMD-compliant](https://github.com/umdjs/umd) bundle supersedes it: This bundle works with many module systems (AMD, CommonJS, etc), or falls back to instantiating a global object (peaks) if no module system is found.
This PR modifies the build to output a single UMD module, and updates the README.md installation instructions using the script-tag to reflect this (though I think the steps should not have changed, but the README …
=> Modified build to output a single UMD module.

README.md, index.html, src/main.js, src/main/views/waveform.zoomview.js
The time label on the playhead used to be visible on the zoomview, I think it was lost with this refactor a6a724894b3291691ae7342b8b62afce6539aac5.  Was that intentional?
=> Restore playhead time label on the zoom view

index.html, src/main/views/playhead-layer.js, src/main/views/waveform.zoomview.js
Currently, when zoomview receives a timeupdate event from the player, it calls `_playheadLayer.syncPlayhead`.  However, if a play animation is present (from `PlayheadLayer.playFrom`), that will immediately call syncPlayhead again with the time value based on when playFrom was last called.
This commit calls playFrom on each timeupdate event, which eliminates drift and ensures that the playhead is in sync with any changes made to the audio node (eg if the audio node is playing and you change audio.currentTime externally to peaks.js).
WDYT?
=> Keep playhead layer in sync with timeupdate events

src/main/views/waveform.overview.js
Sorry - one more fix for the playhead animations. 
If you play and then seek by clicking in the `zoomview`, the playhead in the `overview` view jumps around.  It's keeping the original play animation but also receiving timeupdate events for a different time.  This commit ensures the two are in sync.
It wasn't visible in my original demo page because it was a long audio file, so the overview waveform was extremely zoomed out.  It's more obvious with a shorter clip here - https://codepen.io/jdelStrother/pen/QOaVax?editors=1010.
[WaveformOverview & WaveformZoomview are building up quite a bit of duplication.  How do you feel about extracting the duplication to a shared set of functions?]
=> Fix the overview playhead not keeping in sync following a seek

README.md, src/main/views/points-layer.js, src/main/waveform/waveform.mixins.js
This PR adds support for two new Point events: `points.mouseover` and `points.mouseleave`.
=> Added pointer.mouseover and pointer.mouseleave events

src/main/waveform/waveform.core.js
ReferenceError: Can't find variable: AudioContext
=> fix init error in safari

src/main/views/points-layer.js, src/main/waveform/waveform.mixins.js
Good morning, this should fix this error:
> Uncaught TypeError: Cannot read property 'getX' of undefined
at PointsLayer._onPointHandleDragMove (points-layer.js:72)
at Konva.Group.<anonymous> (waveform.mixins.js:115)
at Konva.Group._fire (konva.js:4329)
at Konva.Group._fireAndBubble (konva.js:4291)
at Konva.Group.fire (konva.js:3772)
at HTMLHtmlElement._drag (konva.js:12447)
and also makes the point marker live moving in the overview while dragging in zoomview.
Thanks
=> Fix dragmove event and add live updating of point when dragging.

src/main/waveform/waveform.core.js
When use `AudioContext` to generate the Peak,  and the `mediaSourceUrl` is null at the first time,  the `canplay` event listener will be bind. 
As we know, `canplay` event will be emit not only once, it can be emit so many times when we seek the video. 
https://github.com/bbc/peaks.js/blob/a7f11efe8fee6b40d9fadfb4ed17c47c68efde57/src/main/waveform/waveform.core.js#L179-L196
This code will cause `WaveformData` rebuild many times, we will not only lost the points marked before, but also each rebuild will add  many event listeners, may be memory leak at last. 
Add the `canplay` event listener by `once` can fix the problem maybe.
#208
=> When use `AudioContext`, only call requestAudioAndBuildWaveformData once

src/main/views/helpers/mousedraghandler.js
call event.preventDefault() in touchend event handler to prevent the handling of browser generated mouse events on mobile devices, see https://github.com/bbc/peaks.js/issues/251
=> supress mouse events event after touch events

README.md, karma.conf.js, package.json, test/unit/api-player-spec.js, test/unit/api-points-spec.js, test/unit/api-segments-spec.js, test/unit/api-spec.js, test/unit/api-view-apec.js, test/unit/api-views-spec.js, test/unit/api-zoom-spec.js, test/unit/point-spec.js, test/unit/segment-spec.js, test/unit/utils-spec.js, test/unit/waveform-builder-spec.js, test/unit/waveform-segments-spec.js
close #266 - allows running selected test suites by command line argument
examples:
```
npm test -- --glob=api-player-spec.js
```
```
npm run test-watch -- --glob=api-player-spec.js
```
```
npm test -- --glob=waveform*.js
```
=> allow glob for testing

README.md
This is a minor README change to let the user know that they can't run the demos with (`npm start`) without installing dependencies first (`npm install`).
=> Updated README to include install note

peaks.js.d.ts
The changes from version 0.14.3 were missing.
- overviewHighlightOffset
- overviewHighlightRectangleColor -> overviewHighlightColor
=> Update typescript definitions for 0.14.3 changes

peaks.js.d.ts
Changes from 0.18.0. were missing:
Views API:
* destroyOverview()
* destroyZoomview()
View API:
* setZoom
* setStartTime
Further Improvements:
* name parameter in views.getView(name) is checked at compile time
* options parameter in setZoom(options) is checked at compile time. (Either scale or seconds is given and is either a number or string "auto").
=> Update typescript definitions for 0.18.0 changes

peaks.js.d.ts
I noticed I was getting TypeScript errors when using this event, and realized it was wrong in the typedef file.
=> Fixed player.playing event name in .d.ts file

README.md, demo/index.html, peaks.js.d.ts, src/mediaelement-player.js, src/player.js
This is emitted when the audio element itself emits an "ended" event, as well as when a segment played by `playSegment()` reaches the endpoint.
=> Added player.ended event

README.md
I copied the code snippet from the README while setting up PeakJS and was confused why I was getting an error. Turns out there are two code examples that incorrectly reference the HTML element IDs as `overview-waveform` and `zoomview-waveform` but they are set up in the very first example as `X-container` instead of `X-waveform`.
This PR updates these two examples to reference `overview-container` and `zoomview-container` to be consistent with all the other examples.
=> Update README code example to use correct element ID

.eslintrc.js
Before this, when using peaks in a subdirectory of a larger project, peak's linting rules would combine with the parent project linting rules, which doesn't seem desirable.
=> Add root:true to eslintrc.js

peaks.js.d.ts, src/main.js
overviewHighlightColor stopped working in https://github.com/bbc/peaks.js/commit/93c7024ccfccfbfa13de2addac644492fb2219cf - this fixes that and updates the types to cover the new options structure.
(Update: actually, overviewHighlightColor continued working as long as you specified both it and the overviewHighlightOffset. But it was no longer applying the default values for either, and they couldn't be specified via the new 'options.overview' option.)
=> Fix overviewHighlightColor, update .d.ts

README.md
After using Peaks.js, I find 3 "errors" in JS snippets and I found the "Using Peaks.js in your own project" section not really clear for a beginner.
This PR is only about the README file:
- 3 typos in Javascript snippets
- Add one step in the user guide ("Using Peaks.js in your own project" section)
- Refactor the "Using Peaks.js in your own project" section
=> Fix JS typo and add details in installation in README

peaks.js.d.ts, src/points-layer.js, src/segment-shape.js, src/segments-layer.js, src/waveform-axis.js, src/waveform-overview.js, src/waveform-points.js, src/waveform-segments.js, src/waveform-zoomview.js, test/unit/api-points-spec.js, test/unit/api-segments-spec.js
This is a bit of a grab-bag of commits broken out from my segment-dragging branch, which I think are useful whether or not we decide to merge segment-dragging.  I can break them out into separate PRs if you'd prefer - each commit is relatively independent so it might make more sense to review that way.
Do you consider methods like WaveformZoomview.prototype.pixelsToTime to be public? They have jsdoc comments and don't have a "_" prefix, but conversely they aren't in the main documentation or in the Typescript defs. If they're public I'll add them to peaks.d.ts, but I didn't want to add to the public API surface area more than necessary.
I also wanted to check about the removal of some `Math.floor`s - eg here: 
```diff
--- a/src/waveform-zoomview.js
+++ b/src/waveform-zoomview.js
@@ …
```
=> Reduce frame offset wrangling

demo/zoomable-waveform.html, src/main.js, src/player.js, src/waveform-builder.js, src/waveform-zoomview.js, test/unit/api-player-spec.js, test/unit/api-view-spec.js
It seems that without `logger` defined in the `options` object, an error is thrown:
```sh
Uncaught TypeError: this._peaks.logger is not a function
at WaveformZoomView.setZoom (peaks.js:14546)
at zoomable-waveform.html:160
at peaks.js:16876
at peaks.js:16162
at Worker.listener (peaks.js:16125)
```
Adding a `logger` definition makes the example work again.
Before submitting a pull request, please read our [contributor guidelines](https://github.com/bbc/peaks.js/blob/master/CONTRIBUTING.md).
Pull requests that don't follow the guidelines risk not being accepted.
=> Add logger to options

README.md
Rename "ES module bundle" to "Install to npm" to make the TOC jump link work. 
I decided to rename the header of the documentation chapter, since a further explaining text uses "ES module bundler" anyway.
=> Fix a TOC jump link

README.md, demo/index.html, peaks.js.d.ts, src/waveform-overview.js, src/waveform-zoomview.js
See #421. This PR adds new functions to allow applications to disable seek and drag/scroll interactions.
To disable drag/scroll in the zoomable waveform view:
```javascript
const zoomview = peaksInstance.views.getView('zoomview');
zoomview.enableDragScroll(false); // or true to re-enable
```
To disable seek on click (actually on mouse-up):
```javascript
const overview = peaksInstance.views.getView('zoomview');
const zoomview = peaksInstance.views.getView('zoomview');
overview.enableSeek(false); // or true to re-enable
zoomview.enableSeek(false);
```
How is this, @rowild?
=> Added functions to disable seek and drag/scroll interactions

README.md, demo/index.html, demo/webaudio.html, peaks.js.d.ts, src/point-marker.js, src/points-layer.js, src/segment-marker.js, src/segment-shape.js, src/segments-layer.js, src/waveform-overview.js, src/waveform-zoomview.js
See issue #414. This changes a number of event handlers to also expose the MouseEvent, so that applications can, for example, check the keyboard state. This is a breaking API change and so users will need to update their code, as shown below.
- `overview.click`, `overview.dblclick`, 
- `zoomview.click`, `zoomview.dblclick`
```js
// Before
peaks.on('zoomview.click', function(time) {
console.log(time);
});
// After
peaks.on('zoomview.click', function(event) {
console.log(event.time);
console.log(event.evt.ctrlKey);
console.log(event.evt.shiftKey);
});
```
- `points.dragstart`, `points.dragmove`, `points.dragend`
- `points.mouseenter`, `points.mouseleave`
- `points.click`, `points.dblclick`
```js
// Before
peaks.on('point.click', function(time) {
console.log(time);
});
// After …
```
=> Changed event handlers to also expose MouseEvent

peaks.js.d.ts
This PR fixes a little typo in the typescript definition: The waveform cache is currently not labelled as optional in typescript, even though it is intended to be optional.
=> label waveformCache prop as optional

src/waveform-zoomview.js
Apparently I didn't review https://github.com/bbc/peaks.js/issues/454 carefully enough - I've come to realise it makes scrolling pretty awful on my Macbook Pro in Safari, where 50% of the time a horizontal swipe would try to navigate the page backwards & forwards rather than scrolling the waveform.
=> Improve horizontal scrolling on trackpads

README.md, demo/index.html, src/highlight-layer.js, src/main.js, src/waveform-overview.js
BBC Team,
First off, thanks for this incredible library. Secondly, I apologize for not discussing this prior to the PR, but I hope this will be received well.
I have a strong desire to further visually customize Peaks.js. In this PR, the highlight region. Here is an example of my particular design usecase. Might be worth exploring a way to extend Konva options for every Konva object but honestly, this looks beautiful to me and I'm very happy with the ability to set these options.
=> feat(): highlight region styles

package-lock.json, package.json
Konva 9.0 / 9.1 have been working fine for us with peaks. How about relaxing the version range?
=> Relax konva version range

peaks.js.d.ts
This change just adds the `zoomview.update` event to the typescript declarations.
=> Updated TypeScript declarations
